name: 'GitHub Space Shooter'
description: 'Transform your GitHub contribution graph into a space shooter game GIF or embeddable HTML'
author: 'zane'

branding:
  icon: 'navigation-2'
  color: 'black'

inputs:
  github-token:
    description: 'GitHub token for fetching contribution data (usually secrets.GITHUB_TOKEN)'
    required: true
  username:
    description: 'GitHub username to generate game for (defaults to repository owner)'
    required: false
    default: ${{ github.repository_owner }}
  output-path:
    description: 'Path where the GIF should be saved'
    required: false
    default: 'gh-space-shooter.gif'
  strategy:
    description: 'Enemy attack strategy (column, row, or random)'
    required: false
    default: 'random'
  fps:
    description: 'Frames per second for the animation (default: 40)'
    required: false
    default: '40'
  write-dataurl-to:
    description: 'Write WebP as HTML <img> data URL to text file (mutually exclusive with output-path)'
    required: false
  commit-message:
    description: 'Commit message for the GIF update'
    required: false
    default: 'Update space shooter game GIF'

outputs:
  output-file:
    description: 'Path to the generated output file (GIF, WebP, or HTML data URL file)'
    value: ${{ steps.generate.outputs.output-file }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install gh-space-shooter
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install gh-space-shooter

    - name: Generate game
      id: generate
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ -n "${{ inputs.write-dataurl-to }}" ]; then
          gh-space-shooter ${{ inputs.username }} \
            --write-dataurl-to ${{ inputs.write-dataurl-to }} \
            --strategy ${{ inputs.strategy }} \
            --fps ${{ inputs.fps }}
          echo "output-file=${{ inputs.write-dataurl-to }}" >> $GITHUB_OUTPUT
        else
          gh-space-shooter ${{ inputs.username }} \
            --output ${{ inputs.output-path }} \
            --strategy ${{ inputs.strategy }} \
            --fps ${{ inputs.fps }}
          echo "output-file=${{ inputs.output-path }}" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [ -n "${{ inputs.write-dataurl-to }}" ]; then
          git add ${{ inputs.write-dataurl-to }}
        else
          git add ${{ inputs.output-path }}
        fi
        git diff --staged --quiet || git commit -m "${{ inputs.commit-message }}"
        git push
